name: money_management_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  hive: 2.2.3
  hive_flutter: 1.1.0
  intl: 0.20.2

dev_dependencies:
  build_runner: 2.4.15
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1

flutter:
  uses-material-design: true
